# Build and push artifacts
name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Ninja
      run: choco install -y ninja

    - name: CMake generate
      shell: bash
      env:
        ARTIFACT_NAME: mrst-${{ runner.os }}
      run: |
        cmake -S . -B build -GNinja \
          -DCMAKE_INSTALL_PREFIX=$ARTIFACT_NAME \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_TESTING=OFF \
          -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++
    - name: Build
      shell: bash
      run: cmake --build build --target install --parallel --verbose
    
    - uses: actions/upload-artifact@v4
      if: github.ref == 'refs/heads/main' && github.repository == 'em-eight/mrst'
      with:
        name: mrst-${{ runner.os }}
        path: mrst-${{ runner.os }}
